apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits: 
        memory: "200Mi"
      requests:
        memory: "200Mi"
      